apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: increment-api-ingress
  namespace: ns-04
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: dcs-04.hse.ru
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: increment-api
                port:
                  number: 80
